# Generated by Django 3.2.7 on 2021-09-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_grocerylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='status',
            field=models.IntegerField(),
        ),
    ]
